### ISSUE TITLE
Decide how to handle window switch events

### ISSUE THREAD

**Issue by winstonpuckett** [bobbypuckett/miomob#4]
Currently the main window coordinates the switching of pages. It feels... Unintentional. A discussion needs to happen around how those events SHOULD be handled and whether that functionality needs to move or if there is something better that can be done
- [ ] Refactor so it looks intentional

**Comment by ivy-puckett** [comment]
This says what I was thinking:
https://stackoverflow.com/questions/2700796/can-you-use-data-binding-with-the-content-property-of-a-wpf-frame

tl;dr Let the viewmodel handle dispatching commands to the view
